### ISSUE TITLE
Allow canceling dragging actions

### ISSUE THREAD

**Issue by yanisslav** [telerik/kendo-draggable#55]
This is related to our task of implementing an OnDragStart event that should be cancellable.

See: https://github.com/telerik/blazor/issues/5994

We need to introduce a mechanism that can cancel the drag operation. This enhancement will enable us to expose an `OnDragStart` event that users can choose to cancel, thus preventing the end user from dragging items conditionally.

===

Such function seems to have already been discussed here: https://github.com/telerik/kendo-draggable/issues/52

cc: @telerik/kendo-draggable-reviewers

**Comment by Stamo-Gochev** [comment]
The proposal is generally valid, but we can extend the spec with other drag events, e.g. "dragEnd", "dragOver", etc. - we can follow what the [HTML 5 Drag&Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API) covers and which events are preventable.
